"""Runtime View and server validation for the semantic query contract.

This package turns retrieval candidates into what HCX is allowed to see, and
decides whether what HCX submitted may execute. It reads the Semantic Registry
and nothing physical: no table, column, join or SQL appears anywhere in it.

Everything defined here is provisional. ``CONTRACT_STATUS`` says so, and it
travels inside every payload and every result, because a reason code that looks
settled is one another workstream will start depending on.
"""

from .canonicalize import (
    AGGREGATION_FUNCTIONS,
    CODE_AGGREGATION_AMBIGUOUS,
    CODE_AGGREGATION_UNSUPPORTED,
    CODE_COMPARISON_AMBIGUOUS,
    CODE_COMPARISON_UNSUPPORTED,
    CODE_DIRECTION_AMBIGUOUS,
    CODE_DIRECTION_UNSUPPORTED,
    CODE_FIELD_METADATA_UNAVAILABLE,
    CODE_LIMIT_AMBIGUOUS,
    CODE_LIMIT_IS_PROPORTION,
    CODE_LIMIT_NOT_POSITIVE,
    CODE_LIMIT_UNSUPPORTED,
    CODE_NEGATED,
    CODE_OPERATION_NOT_ALLOWED,
    CODE_UNIT_NOT_CANONICALIZABLE,
    CODE_VALUE_UNIT_MISMATCH,
    CODE_VALUE_UNSUPPORTED,
    COMPARISON_OPERATORS,
    DIRECTIONS,
    IMPLEMENTED_CANONICALIZERS,
    AggregationResult,
    ComparisonResult,
    DirectionResult,
    Failure,
    FieldMetadata,
    LimitResult,
    RequirementCanonicalization,
    TypedValue,
    canonicalize_aggregation,
    canonicalize_comparison,
    canonicalize_direction,
    canonicalize_limit,
    canonicalize_ordering,
    canonicalize_requirement,
    field_metadata,
)
from .contract import (
    AVAILABLE_CANONICALIZERS,
    CONTRACT_STATUS,
    DATASET_GRAINS,
    DATASET_GRAINS_SOURCE,
    DECISION_AMBIGUOUS,
    DECISION_MAPPED,
    DECISION_UNRESOLVED,
    REQUIREMENT_KINDS,
    REQUIREMENT_KINDS_SOURCE,
    REQUIREMENT_STATUSES,
    STATUS_AMBIGUOUS,
    STATUS_MAPPED,
    STATUS_UNRESOLVED,
)
from .execution_facts import (
    BindingSummary,
    CapabilityResolution,
    ExecutionFacts,
    ExecutionRegistryFacts,
    NoExecutionFacts,
    TargetCapabilitySummary,
)
from .grouped_flat import (
    CODE_CONFLICTING_RECORD,
    CODE_DUPLICATE_RECORD,
    CODE_ORPHAN_RECORD,
    CODE_UNKNOWN_DETAIL_KIND,
    CODE_UNKNOWN_ROLE,
    DETAIL_KINDS,
    REF_ROLES,
    assemble_submission_payload,
    grouped_flat_schema,
    grouped_flat_slots,
    parse_grouped_flat,
    to_grouped_flat,
)
from .hcx_wire import (
    HCX_WIRE_DROPPED_KEYWORDS,
    HCX_WIRE_KEYWORDS,
    HcxWireError,
    keyword_vocabulary,
    project_for_hcx,
)
from .model_response import model_response

# ``hcx_bridge`` and ``line_records`` are deliberately absent. All three
# notations publish the same names — an envelope property, a guidance
# renderer, a tool-argument parser — and only one of them can be the
# package's wire. Since 2026-09-01 that is the one-line notation, because
# that is what the provider was observed writing on 2026-08-31 and again on
# 2026-09-01. The other two stay in the tree, and their tests import them
# from their own modules rather than from here.
from .one_line_records import (
    CODE_DUPLICATE_KEY,
    CODE_MALFORMED_KEY_LINE,
    CODE_STRAY_LINE,
    CODE_UNKNOWN_RECORD,
    CODE_UNREPRESENTABLE_VALUE,
    CODE_UNSUPPORTED_LINE_BREAK,
    ENVELOPE_PROPERTY,
    ONE_LINE_DIAGNOSTIC_FIELDS,
    one_line_envelope_diagnostics,
    one_line_parameters_schema,
    one_line_submission_guidance,
    parse_one_line_submission,
    parse_tool_arguments,
    read_one_line_records,
    render_one_line_records,
)
from .query import (
    Submission,
    SubmittedAggregation,
    SubmittedCondition,
    SubmittedOrdering,
    SubmittedQuery,
    SubmittedRelationship,
    SubmittedRequirement,
    parse_submission,
)
from .refs import RefCollisionError, RefError, RefMinter
from .registry_facts import RegistryFacts, RegistryFactsError
from .schema import (
    SUBMISSION_SCHEMA,
    hcx_tool_definition,
    hcx_wire_schema,
    tool_definition,
)
from .spans import CODE_SPAN_ALIGNMENT_FAILED, align, aligned
from .validate import (
    CODE_CANONICALIZATION_REFUSED,
    CODE_CANONICALIZER_UNAVAILABLE,
    CODE_CROSS_FAMILY_FIELD,
    CODE_CROSS_FAMILY_PREDICATE,
    CODE_DIRECTION_UNDECIDABLE,
    CODE_EMPTY_REQUIREMENT,
    CODE_ENTITY_UNRESOLVED,
    CODE_FIELD_SCOPE_UNPROVEN,
    CODE_GRAIN_MISMATCH,
    CODE_MISSING_SOURCE_SPAN,
    CODE_MISSING_TARGET,
    CODE_REF_KIND_MISMATCH,
    CODE_RELATION_TARGET_MISMATCH,
    CODE_REQUIREMENT_AMBIGUOUS,
    CODE_REQUIREMENT_INCOMPLETE,
    CODE_REQUIREMENT_UNRESOLVED,
    CODE_UNACCOUNTED_SPAN,
    CODE_UNKNOWN_REF,
    CanonicalPlan,
    ValidationIssue,
    ValidationResult,
    validate,
)
from .view import (
    BudgetError,
    CandidateBudget,
    CandidateProposal,
    EntityMention,
    EntityResolver,
    NullEntityResolver,
    RuntimeView,
    ViewError,
    build_runtime_view,
)

__all__ = [
    "AGGREGATION_FUNCTIONS",
    "AVAILABLE_CANONICALIZERS",
    "CODE_AGGREGATION_AMBIGUOUS",
    "CODE_AGGREGATION_UNSUPPORTED",
    "CODE_CANONICALIZATION_REFUSED",
    "CODE_CANONICALIZER_UNAVAILABLE",
    "CODE_COMPARISON_AMBIGUOUS",
    "CODE_COMPARISON_UNSUPPORTED",
    "CODE_CONFLICTING_RECORD",
    "CODE_CROSS_FAMILY_FIELD",
    "CODE_CROSS_FAMILY_PREDICATE",
    "CODE_DIRECTION_AMBIGUOUS",
    "CODE_DIRECTION_UNDECIDABLE",
    "CODE_DIRECTION_UNSUPPORTED",
    "CODE_DUPLICATE_KEY",
    "CODE_DUPLICATE_RECORD",
    "CODE_EMPTY_REQUIREMENT",
    "CODE_ENTITY_UNRESOLVED",
    "CODE_FIELD_METADATA_UNAVAILABLE",
    "CODE_FIELD_SCOPE_UNPROVEN",
    "CODE_GRAIN_MISMATCH",
    "CODE_LIMIT_AMBIGUOUS",
    "CODE_LIMIT_IS_PROPORTION",
    "CODE_LIMIT_NOT_POSITIVE",
    "CODE_LIMIT_UNSUPPORTED",
    "CODE_MALFORMED_KEY_LINE",
    "CODE_MISSING_SOURCE_SPAN",
    "CODE_MISSING_TARGET",
    "CODE_NEGATED",
    "CODE_OPERATION_NOT_ALLOWED",
    "CODE_ORPHAN_RECORD",
    "CODE_REF_KIND_MISMATCH",
    "CODE_RELATION_TARGET_MISMATCH",
    "CODE_REQUIREMENT_AMBIGUOUS",
    "CODE_REQUIREMENT_INCOMPLETE",
    "CODE_REQUIREMENT_UNRESOLVED",
    "CODE_SPAN_ALIGNMENT_FAILED",
    "CODE_STRAY_LINE",
    "CODE_UNACCOUNTED_SPAN",
    "CODE_UNIT_NOT_CANONICALIZABLE",
    "CODE_UNKNOWN_DETAIL_KIND",
    "CODE_UNKNOWN_RECORD",
    "CODE_UNKNOWN_REF",
    "CODE_UNKNOWN_ROLE",
    "CODE_UNREPRESENTABLE_VALUE",
    "CODE_UNSUPPORTED_LINE_BREAK",
    "CODE_VALUE_UNIT_MISMATCH",
    "CODE_VALUE_UNSUPPORTED",
    "COMPARISON_OPERATORS",
    "CONTRACT_STATUS",
    "DATASET_GRAINS",
    "DATASET_GRAINS_SOURCE",
    "DECISION_AMBIGUOUS",
    "DECISION_MAPPED",
    "DECISION_UNRESOLVED",
    "DETAIL_KINDS",
    "DIRECTIONS",
    "ENVELOPE_PROPERTY",
    "HCX_WIRE_DROPPED_KEYWORDS",
    "HCX_WIRE_KEYWORDS",
    "IMPLEMENTED_CANONICALIZERS",
    "ONE_LINE_DIAGNOSTIC_FIELDS",
    "REF_ROLES",
    "REQUIREMENT_KINDS",
    "REQUIREMENT_KINDS_SOURCE",
    "REQUIREMENT_STATUSES",
    "STATUS_AMBIGUOUS",
    "STATUS_MAPPED",
    "STATUS_UNRESOLVED",
    "SUBMISSION_SCHEMA",
    "AggregationResult",
    "BindingSummary",
    "BudgetError",
    "CandidateBudget",
    "CandidateProposal",
    "CanonicalPlan",
    "CapabilityResolution",
    "ComparisonResult",
    "DirectionResult",
    "EntityMention",
    "EntityResolver",
    "ExecutionFacts",
    "ExecutionRegistryFacts",
    "Failure",
    "FieldMetadata",
    "HcxWireError",
    "LimitResult",
    "NoExecutionFacts",
    "NullEntityResolver",
    "RefCollisionError",
    "RefError",
    "RefMinter",
    "RegistryFacts",
    "RegistryFactsError",
    "RequirementCanonicalization",
    "RuntimeView",
    "Submission",
    "SubmittedAggregation",
    "SubmittedCondition",
    "SubmittedOrdering",
    "SubmittedQuery",
    "SubmittedRelationship",
    "SubmittedRequirement",
    "TargetCapabilitySummary",
    "TypedValue",
    "ValidationIssue",
    "ValidationResult",
    "ViewError",
    "align",
    "aligned",
    "assemble_submission_payload",
    "build_runtime_view",
    "canonicalize_aggregation",
    "canonicalize_comparison",
    "canonicalize_direction",
    "canonicalize_limit",
    "canonicalize_ordering",
    "canonicalize_requirement",
    "field_metadata",
    "grouped_flat_schema",
    "grouped_flat_slots",
    "hcx_tool_definition",
    "hcx_wire_schema",
    "keyword_vocabulary",
    "model_response",
    "one_line_envelope_diagnostics",
    "one_line_parameters_schema",
    "one_line_submission_guidance",
    "parse_grouped_flat",
    "parse_one_line_submission",
    "parse_submission",
    "parse_tool_arguments",
    "project_for_hcx",
    "read_one_line_records",
    "render_one_line_records",
    "to_grouped_flat",
    "tool_definition",
    "validate",
]
