"""Runtime View and server validation for the semantic query contract.

This package turns retrieval candidates into what HCX is allowed to see, and
decides whether what HCX submitted may execute. It reads the Semantic Registry
and nothing physical: no table, column, join or SQL appears anywhere in it.

Everything defined here is provisional. ``CONTRACT_STATUS`` says so, and it
travels inside every payload and every result, because a reason code that looks
settled is one another workstream will start depending on.
"""

from .contract import (
    AVAILABLE_CANONICALIZERS,
    CONTRACT_STATUS,
    DATASET_GRAINS,
    DATASET_GRAINS_SOURCE,
    DECISION_AMBIGUOUS,
    DECISION_MAPPED,
    DECISION_UNRESOLVED,
    REQUIREMENT_KINDS,
    REQUIREMENT_KINDS_SOURCE,
    REQUIREMENT_STATUSES,
    STATUS_AMBIGUOUS,
    STATUS_MAPPED,
    STATUS_UNRESOLVED,
)
from .execution_facts import (
    BindingSummary,
    CapabilityResolution,
    ExecutionFacts,
    ExecutionRegistryFacts,
    NoExecutionFacts,
    TargetCapabilitySummary,
)
from .grouped_flat import (
    CODE_CONFLICTING_RECORD,
    CODE_DUPLICATE_RECORD,
    CODE_ORPHAN_RECORD,
    CODE_UNKNOWN_DETAIL_KIND,
    CODE_UNKNOWN_ROLE,
    DETAIL_KINDS,
    REF_ROLES,
    assemble_submission_payload,
    grouped_flat_schema,
    grouped_flat_slots,
    parse_grouped_flat,
    to_grouped_flat,
)
from .hcx_wire import (
    HCX_WIRE_DROPPED_KEYWORDS,
    HCX_WIRE_KEYWORDS,
    HcxWireError,
    keyword_vocabulary,
    project_for_hcx,
)
from .model_response import model_response
from .query import (
    Submission,
    SubmittedAggregation,
    SubmittedCondition,
    SubmittedOrdering,
    SubmittedQuery,
    SubmittedRelationship,
    SubmittedRequirement,
    parse_submission,
)
from .refs import RefCollisionError, RefError, RefMinter
from .registry_facts import RegistryFacts, RegistryFactsError
from .schema import (
    SUBMISSION_SCHEMA,
    hcx_tool_definition,
    hcx_wire_schema,
    tool_definition,
)
from .spans import align, aligned
from .validate import (
    CODE_CANONICALIZER_UNAVAILABLE,
    CODE_CROSS_FAMILY_FIELD,
    CODE_CROSS_FAMILY_PREDICATE,
    CODE_DIRECTION_UNDECIDABLE,
    CODE_EMPTY_REQUIREMENT,
    CODE_ENTITY_UNRESOLVED,
    CODE_FIELD_SCOPE_UNPROVEN,
    CODE_GRAIN_MISMATCH,
    CODE_MISSING_SOURCE_SPAN,
    CODE_MISSING_TARGET,
    CODE_REF_KIND_MISMATCH,
    CODE_RELATION_TARGET_MISMATCH,
    CODE_REQUIREMENT_AMBIGUOUS,
    CODE_REQUIREMENT_INCOMPLETE,
    CODE_REQUIREMENT_UNRESOLVED,
    CODE_SPAN_ALIGNMENT_FAILED,
    CODE_UNACCOUNTED_SPAN,
    CODE_UNKNOWN_REF,
    CanonicalPlan,
    ValidationIssue,
    ValidationResult,
    validate,
)
from .view import (
    BudgetError,
    CandidateBudget,
    CandidateProposal,
    EntityMention,
    EntityResolver,
    NullEntityResolver,
    RuntimeView,
    ViewError,
    build_runtime_view,
)

__all__ = [
    "AVAILABLE_CANONICALIZERS",
    "CODE_CANONICALIZER_UNAVAILABLE",
    "CODE_CONFLICTING_RECORD",
    "CODE_CROSS_FAMILY_FIELD",
    "CODE_CROSS_FAMILY_PREDICATE",
    "CODE_DIRECTION_UNDECIDABLE",
    "CODE_DUPLICATE_RECORD",
    "CODE_EMPTY_REQUIREMENT",
    "CODE_ENTITY_UNRESOLVED",
    "CODE_FIELD_SCOPE_UNPROVEN",
    "CODE_GRAIN_MISMATCH",
    "CODE_MISSING_SOURCE_SPAN",
    "CODE_MISSING_TARGET",
    "CODE_ORPHAN_RECORD",
    "CODE_REF_KIND_MISMATCH",
    "CODE_RELATION_TARGET_MISMATCH",
    "CODE_REQUIREMENT_AMBIGUOUS",
    "CODE_REQUIREMENT_INCOMPLETE",
    "CODE_REQUIREMENT_UNRESOLVED",
    "CODE_SPAN_ALIGNMENT_FAILED",
    "CODE_UNACCOUNTED_SPAN",
    "CODE_UNKNOWN_DETAIL_KIND",
    "CODE_UNKNOWN_REF",
    "CODE_UNKNOWN_ROLE",
    "CONTRACT_STATUS",
    "DATASET_GRAINS",
    "DATASET_GRAINS_SOURCE",
    "DECISION_AMBIGUOUS",
    "DECISION_MAPPED",
    "DECISION_UNRESOLVED",
    "DETAIL_KINDS",
    "HCX_WIRE_DROPPED_KEYWORDS",
    "HCX_WIRE_KEYWORDS",
    "REF_ROLES",
    "REQUIREMENT_KINDS",
    "REQUIREMENT_KINDS_SOURCE",
    "REQUIREMENT_STATUSES",
    "STATUS_AMBIGUOUS",
    "STATUS_MAPPED",
    "STATUS_UNRESOLVED",
    "SUBMISSION_SCHEMA",
    "BindingSummary",
    "BudgetError",
    "CandidateBudget",
    "CandidateProposal",
    "CanonicalPlan",
    "CapabilityResolution",
    "EntityMention",
    "EntityResolver",
    "ExecutionFacts",
    "ExecutionRegistryFacts",
    "HcxWireError",
    "NoExecutionFacts",
    "NullEntityResolver",
    "RefCollisionError",
    "RefError",
    "RefMinter",
    "RegistryFacts",
    "RegistryFactsError",
    "RuntimeView",
    "Submission",
    "SubmittedAggregation",
    "SubmittedCondition",
    "SubmittedOrdering",
    "SubmittedQuery",
    "SubmittedRelationship",
    "SubmittedRequirement",
    "TargetCapabilitySummary",
    "ValidationIssue",
    "ValidationResult",
    "ViewError",
    "align",
    "aligned",
    "assemble_submission_payload",
    "build_runtime_view",
    "grouped_flat_schema",
    "grouped_flat_slots",
    "hcx_tool_definition",
    "hcx_wire_schema",
    "keyword_vocabulary",
    "model_response",
    "parse_grouped_flat",
    "parse_submission",
    "project_for_hcx",
    "to_grouped_flat",
    "tool_definition",
    "validate",
]
